[build]
  command = "npx pnpm i --frozen-lockfile --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "dist"

# 1. A hack to skip npm install
# 	@see https://answers.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759/15
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # 1
